### ISSUE TITLE
Week2 : NFT Staking Contract

### ISSUE THREAD

**Issue by dhruvinparikh** [dm4th/metana-course#4]
- [x] `stakeNFT(uint256)` must record the time at which it was staked. It incorrect to rely on the default value `0`.
- [x] This line has bug in function `withdrawERC20(uint256)` -> `require(block.timestamp - _withdrawalTimes[tokenID] >= WITHDRAW_TIME, "You have already withdrawn for this token... You must wait!!");`. The staker can withdraw 10 ERC20 tokens immediately after staking then timer resets which will allow staker to withdraw another 10 tokens after 24 hours. So the requirement to only allow withdrawing 10 tokens every 24 hours does not get fulfilled. You can implement a logic that distribute 10 ERC20 tokens in the form of 0.000115740740741 (=10/86400) tokens per second given 24 hours (or 86400 seconds)
- [x] Because of the above bug, say I can stakeNFT, then immediately withdraw 10 ERC20 tokens and unstake it immediately. This will not fulfill requirement of the NFT to be staked for 24 hours atleast to withdraw 10 ERC20 tokens.
- `uint256 private constant WITHDRAW_TIME = 86400;` can also be declared as `    uint256 private constant WITHDRAW_TIME = 24 hours;`

**Comment by dm4th** [comment]
Ah I get it. I was assuming you could withdraw 10 tokens immediately upon staking for the first time rather than initially needing to wait 24 hours. Not a bad fix, I'll fix those, and deploy/verify on polygon with associate links for you this time.

**Comment by dm4th** [comment]
Re-Commited and had to push to goerli
